In [2]:
import numpy
numpy.__version__

'1.14.2'

In [3]:
import numpy as np

For the pieces of the package discussed here, I'd recommend NumPy version 1.8 or later. By convention, you'll find that most people in the SciPy/PyData world will import NumPy using np as an alias:

# Built In Documentation

IPython gives you the ability to quickly explore the contents of a package (by using the tab-completion feature), as well as the documentation of various functions (using the ? character – Refer back to Help and Documentation in IPython).

To display all the contents of the numpy namespace, you can type this:

In [5]:
 np?

Users of Python are often drawn-in by its ease of use, one piece of which is dynamic typing. While a statically-typed language like C or Java requires each variable to be explicitly declared, a dynamically-typed language like Python skips this specification. For example, in C you might specify a particular operation as follows:

While in Python the equivalent operation could be written this way:

In [7]:
# Python code
result = 0
for i in range(100):
    result += i

Notice the main difference: in C, the data types of each variable are explicitly declared, while in Python the types are dynamically inferred. This means, for example, that we can assign any kind of data to any variable

# A Python Integer Is More Than Just an Integer

The standard Python implementation is written in C. This means that every Python object is simply a cleverly-disguised C structure, which contains not only its value, but other information as well. For example, when we define an integer in Python, such as x = 10000, x is not just a "raw" integer. It's actually a pointer to a compound C structure, which contains several values. Looking through the Python 3.4 source code, we find that the integer (long) type definition effectively looks like this (once the C macros are expanded):

In [8]:
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};

SyntaxError: invalid syntax (<ipython-input-8-c7e6b3212599>, line 1)

A single integer in Python 3.4 actually contains four pieces:

ob_refcnt, a reference count that helps Python silently handle memory allocation and deallocation
ob_type, which encodes the type of the variable
ob_size, which specifies the size of the following data members
ob_digit, which contains the actual integer value that we expect the Python variable to represent.

# Creating Arrays from Python Lists

In [9]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [10]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [11]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [13]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
import random

In [17]:
np.full((3, 5), random.randrange(20, 50, 2))

array([[40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40],
       [40, 40, 40, 40, 40]])

In [16]:
import random 
  
# using choice() to generate a random number from a  
# given list of numbers. 
print ("A random number from list is : ",end="") 
print (random.choice([1, 4, 8, 10, 3])) 
  
# using randrange() to generate in range from 20 
# to 50. The last parameter 3 is step size to skip 
# three numbers when selecting. 
print ("A random number from range is : ",end="") 
print (random.randrange(20, 50, 3)) 

A random number from list is : 3
A random number from range is : 20


In [21]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
np.random.random((3, 3))

array([[0.48877693, 0.66009994, 0.3959971 ],
       [0.43346735, 0.70072221, 0.75265391],
       [0.65288053, 0.67066497, 0.4213738 ]])

In [24]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.19428923, -1.54538447,  0.76676444],
       [ 0.17192528, -2.50085501, -1.22549957],
       [ 0.16595476,  1.45814856, -0.14191227]])

# Variance and standard-deviation of a matrix

Mean is average of a given set of data. Let us consider below example

 2,\ 4,\ 4,\ 4,\ 5,\ 5,\ 7,\ 9 

These eight data points have the mean (average) of 5:

 \frac{2 + 4 + 4 + 4 + 5 + 5 + 7 + 9}{8} = 5. 

 
Variance is sum of squares of differences between all numbers and means.
Deviation for above example. First, calculate the deviations of each data point from the mean, and square the result of each:



 \begin{array}{lll} (2-5)^2 = (-3)^2 = 9 && (5-5)^2 = 0^2 = 0 \\ (4-5)^2 = (-1)^2 = 1 && (5-5)^2 = 0^2 = 0 \\ (4-5)^2 = (-1)^2 = 1 && (7-5)^2 = 2^2 = 4 \\ (4-5)^2 = (-1)^2 = 1 && (9-5)^2 = 4^2 = 16. \\ \end{array} 

variance = \frac{9 + 1 + 1 + 1 + 0 + 0 + 4 + 16}{8} = 4.

 
Standard Deviation is square root of variance. It is a measure of the extent to which data varies from the mean.

Standard Deviation (for above data) = \sqrt{ 4 } = 2
Mean is average of a given set of data. Let us consider below example

 2,\ 4,\ 4,\ 4,\ 5,\ 5,\ 7,\ 9 

These eight data points have the mean (average) of 5:

 \frac{2 + 4 + 4 + 4 + 5 + 5 + 7 + 9}{8} = 5. 

 
Variance is sum of squares of differences between all numbers and means.
Deviation for above example. First, calculate the deviations of each data point from the mean, and square the result of each:



 \begin{array}{lll} (2-5)^2 = (-3)^2 = 9 && (5-5)^2 = 0^2 = 0 \\ (4-5)^2 = (-1)^2 = 1 && (5-5)^2 = 0^2 = 0 \\ (4-5)^2 = (-1)^2 = 1 && (7-5)^2 = 2^2 = 4 \\ (4-5)^2 = (-1)^2 = 1 && (9-5)^2 = 4^2 = 16. \\ \end{array} 

variance = \frac{9 + 1 + 1 + 1 + 0 + 0 + 4 + 16}{8} = 4.

 
Standard Deviation is square root of variance. It is a measure of the extent to which data varies from the mean.

Standard Deviation (for above data) = \sqrt{ 4 } = 2

Why did mathematicians chose square and then square root to find deviation, why not simply take difference of values?
One reason is the sum of differences becomes 0 according to definition of mean. Sum of absolute differences could be an option, but with absolute differences it was difficult to prove many nice theorems
Why did mathematicians chose square and then square root to find deviation, why not simply take difference of values?
One reason is the sum of differences becomes 0 according to definition of mean. Sum of absolute differences could be an option, but with absolute differences it was difficult to prove many nice theorems

Given a matrix of size n*n. We have to calculate variance and standard-deviation of given matrix.

First mean should be calculated by adding sum of each elements of the matrix. After calculating mean, it should be subtracted from each element of the matrix.Then square each term and find out the variance by dividing sum with total elements.
Deviation: It is the square root of the variance.

In [28]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.17205166,  0.99509263,  1.20296718],
       [ 0.13225688, -1.18676213, -2.03375728],
       [-1.5384356 , -0.12300775, -0.81203762]])

In [29]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

# NumPy Standard Data Types

NumPy Standard Data Types

In [32]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)